server:
  port: 8085
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
      metrics:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
resilience4j:
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 5
        maxWaitDuration: 0
    instances:
      atmsBulkhead:
        baseConfig: default
api:
  scheme: https
  host: api.lloydsbank.com
  path: /open-banking/v2.2/atms


