server:
  port: 8085
management:
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
      metrics:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  endpoint:
    health:
      show-details: always
resilience4j:
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 5
        maxWaitDuration: 0
    instances:
      atmsBulkhead:
        baseConfig: default
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
api:
  scheme: https
  host: api.lloydsbank.com
  path: /open-banking/v2.2/atms


