server:
  port: 8085
management:
  security:
    enabled: false
resilience4j:
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 5
        maxWaitDuration: 0
    instances:
      atmsBulkhead:
        baseConfig: default
api:
  scheme: https
  host: api.lloydsbank.com
  path: /open-banking/v2.2/atms


